const CHAR_W: usize = 5;
const CHAR_H: usize = 9;
const PIXEL_BIT: usize = 4;

fn convert(s: &str) -> u8 {
    u8::from_str_radix(&s.replace(|c| c != '.', "1").replace('.', "0"), 2).unwrap()
}

pub fn get_glyph(ch: char) -> Option<[u8; CHAR_H]> {
    match ch {
        '0' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O..OO"),
            convert("O.O.O"),
            convert("OO..O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        '1' => Some([
            convert("....."),
            convert("..O.."),
            convert(".OO.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        '2' => Some([
            convert("....."),
            convert("OOOO."),
            convert("....O"),
            convert("....O"),
            convert("...O."),
            convert("..O.."),
            convert(".O..."),
            convert("OOOOO"),
            convert("....."),
        ]),
        '3' => Some([
            convert("....."),
            convert("OOOO."),
            convert("....O"),
            convert("....O"),
            convert("OOOO."),
            convert("....O"),
            convert("....O"),
            convert("OOOO."),
            convert("....."),
        ]),
        '4' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("OOOOO"),
            convert("....O"),
            convert("....O"),
            convert("....O"),
            convert("....."),
        ]),
        '5' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("O...."),
            convert("O...."),
            convert("OOOO."),
            convert("....O"),
            convert("....O"),
            convert("OOOO."),
            convert("....."),
        ]),
        '6' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...."),
            convert("O...."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        '7' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("....O"),
            convert("....O"),
            convert("...O."),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        '8' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        '9' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'A' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOOO"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'B' => Some([
            convert("....."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("....."),
        ]),
        'C' => Some([
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert(".OOOO"),
            convert("....."),
        ]),
        'D' => Some([
            convert("....."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("....."),
        ]),
        'E' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("O...."),
            convert("O...."),
            convert("OOOOO"),
            convert("O...."),
            convert("O...."),
            convert("OOOOO"),
            convert("....."),
        ]),
        'F' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("O...."),
            convert("O...."),
            convert("OOOOO"),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("....."),
        ]),
        'G' => Some([
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert("O...."),
            convert("O..OO"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'H' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("OOOOO"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'I' => Some([
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        'J' => Some([
            convert("....."),
            convert("...OO"),
            convert("....O"),
            convert("....O"),
            convert("....O"),
            convert("....O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'K' => Some([
            convert("....."),
            convert("O...O"),
            convert("O..O."),
            convert("O.O.."),
            convert("OO..."),
            convert("O.O.."),
            convert("O..O."),
            convert("O...O"),
            convert("....."),
        ]),
        'L' => Some([
            convert("....."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("OOOOO"),
            convert("....."),
        ]),
        'M' => Some([
            convert("....."),
            convert("O...O"),
            convert("OO.OO"),
            convert("O.O.O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'N' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("OO..O"),
            convert("O.O.O"),
            convert("O..OO"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'O' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'P' => Some([
            convert("....."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("....."),
        ]),
        'Q' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O..O."),
            convert(".OO.O"),
            convert("....."),
        ]),
        'R' => Some([
            convert("....."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'S' => Some([
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert("O...."),
            convert(".OOO."),
            convert("....O"),
            convert("....O"),
            convert("OOOO."),
            convert("....."),
        ]),
        'T' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        'U' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'V' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".O.O."),
            convert(".O.O."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        'W' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O.O.O"),
            convert("OO.OO"),
            convert("O...O"),
            convert("....."),
        ]),
        'X' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert(".O.O."),
            convert("..O.."),
            convert(".O.O."),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'Y' => Some([
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert(".O.O."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        'Z' => Some([
            convert("....."),
            convert("OOOOO"),
            convert("....O"),
            convert("...O."),
            convert("..O.."),
            convert(".O..."),
            convert("O...."),
            convert("OOOOO"),
            convert("....."),
        ]),
        'a' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("....O"),
            convert(".OOOO"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....."),
        ]),
        'b' => Some([
            convert("....."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("....."),
        ]),
        'c' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert(".OOOO"),
            convert("....."),
        ]),
        'd' => Some([
            convert("....."),
            convert("....O"),
            convert("....O"),
            convert(".OOOO"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....."),
        ]),
        'e' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("OOOOO"),
            convert("O...."),
            convert(".OOO."),
            convert("....."),
        ]),
        'f' => Some([
            convert("....."),
            convert("..OO."),
            convert(".O..."),
            convert(".O..."),
            convert(".OO.."),
            convert(".O..."),
            convert(".O..."),
            convert(".O..."),
            convert("....."),
        ]),
        'g' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....O"),
            convert("....O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'h' => Some([
            convert("....."),
            convert("O...."),
            convert("O...."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'i' => Some([
            convert("....."),
            convert("..O.."),
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
        ]),
        'j' => Some([
            convert("....."),
            convert("...O."),
            convert("....."),
            convert("...O."),
            convert("...O."),
            convert("...O."),
            convert("...O."),
            convert(".OO.."),
            convert("....."),
        ]),
        'k' => Some([
            convert("....."),
            convert("O...."),
            convert("O..O."),
            convert("O.O.."),
            convert("OO..."),
            convert("O.O.."),
            convert("O..O."),
            convert("O...O"),
            convert("....."),
        ]),
        'l' => Some([
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("....."),
        ]),
        'm' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".O.O."),
            convert("O.O.O"),
            convert("O.O.O"),
            convert("O.O.O"),
            convert("O.O.O"),
            convert("....."),
        ]),
        'n' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("....."),
        ]),
        'o' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'p' => Some([
            convert("....."),
            convert("....."),
            convert("OOOO."),
            convert("O...O"),
            convert("O...O"),
            convert("OOOO."),
            convert("O...."),
            convert("O...."),
            convert("....."),
        ]),
        'q' => Some([
            convert("....."),
            convert("....."),
            convert(".OOOO"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....O"),
            convert("....O"),
            convert("....."),
        ]),
        'r' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("O...."),
            convert("....."),
        ]),
        's' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOOO"),
            convert("O...."),
            convert(".OOO."),
            convert("....O"),
            convert("OOOO."),
            convert("....."),
        ]),
        't' => Some([
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert(".OOO."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("....."),
        ]),
        'u' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'v' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert(".O.O."),
            convert(".O.O."),
            convert("..O.."),
            convert("....."),
        ]),
        'w' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("O.O.O"),
            convert("O.O.O"),
            convert("O.O.O"),
            convert("O.O.O"),
            convert(".O.O."),
            convert("....."),
        ]),
        'x' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("O...O"),
            convert(".O.O."),
            convert("..O.."),
            convert(".O.O."),
            convert("O...O"),
            convert("....."),
        ]),
        'y' => Some([
            convert("....."),
            convert("....."),
            convert("O...O"),
            convert("O...O"),
            convert("O...O"),
            convert(".OOOO"),
            convert("....O"),
            convert(".OOO."),
            convert("....."),
        ]),
        'z' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("OOOOO"),
            convert("...O."),
            convert("..O.."),
            convert(".O..."),
            convert("OOOOO"),
            convert("....."),
        ]),
        '!' => Some([
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
            convert("..O.."),
            convert("....."),
        ]),
        '"' => Some([
            convert("....."),
            convert(".O.O."),
            convert(".O.O."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '#' => Some([
            convert("....."),
            convert(".O.O."),
            convert(".O.O."),
            convert("OOOOO"),
            convert(".O.O."),
            convert("OOOOO"),
            convert(".O.O."),
            convert(".O.O."),
            convert("....."),
        ]),
        '$' => Some([
            convert("....."),
            convert("..O.."),
            convert("OOOO."),
            convert(".O..O"),
            convert("..O.."),
            convert("O..O."),
            convert(".OOOO"),
            convert("..O.."),
            convert("....."),
        ]),
        '%' => Some([
            convert("....."),
            convert("OO..O"),
            convert("OO.O."),
            convert("...O."),
            convert("..O.."),
            convert(".O..."),
            convert(".O.OO"),
            convert("O..OO"),
            convert("....."),
        ]),
        '&' => Some([
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert(".O..."),
            convert("O.O.O"),
            convert("O..O."),
            convert(".OO.O"),
            convert("....."),
        ]),
        '\'' => Some([
            convert("....."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '(' => Some([
            convert("....."),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("....."),
        ]),
        ')' => Some([
            convert("....."),
            convert(".O..."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert(".O..."),
            convert("....."),
        ]),
        '-' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '=' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OOO."),
            convert("....."),
            convert(".OOO."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '~' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".O..."),
            convert("O.O.O"),
            convert("...O."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '^' => Some([
            convert("....."),
            convert("..O.."),
            convert(".O.O."),
            convert("O...O"),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        ';' => Some([
            convert("....."),
            convert("....."),
            convert(".OO.."),
            convert(".OO.."),
            convert("....."),
            convert(".OO.."),
            convert(".OO.."),
            convert("..O.."),
            convert("....."),
        ]),
        ':' => Some([
            convert("....."),
            convert("....."),
            convert(".OO.."),
            convert(".OO.."),
            convert("....."),
            convert(".OO.."),
            convert(".OO.."),
            convert("....."),
            convert("....."),
        ]),
        '[' => Some([
            convert("....."),
            convert("..OO."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..OO."),
            convert("....."),
        ]),
        ']' => Some([
            convert("....."),
            convert(".OO.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert(".OO.."),
            convert("....."),
        ]),
        '{' => Some([
            convert("....."),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert(".O..."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("....."),
        ]),
        '}' => Some([
            convert("....."),
            convert(".O..."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert(".O..."),
            convert("....."),
        ]),
        '@' => Some([
            convert("....."),
            convert(".OOOO"),
            convert("O...O"),
            convert("O.OOO"),
            convert("O.O.O"),
            convert("O.OOO"),
            convert("O...."),
            convert(".OOO."),
            convert("....."),
        ]),
        '`' => Some([
            convert("....."),
            convert(".O..."),
            convert("..O.."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '+' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("..O.."),
            convert(".OOO."),
            convert("..O.."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        '*' => Some([
            convert("....."),
            convert("....."),
            convert("..O.."),
            convert("O.O.O"),
            convert(".OOO."),
            convert("..O.."),
            convert(".O.O."),
            convert("....."),
            convert("....."),
        ]),
        '<' => Some([
            convert("....."),
            convert("....."),
            convert("...OO"),
            convert(".OO.."),
            convert("O...."),
            convert(".OO.."),
            convert("...OO"),
            convert("....."),
            convert("....."),
        ]),
        '>' => Some([
            convert("....."),
            convert("....."),
            convert("OO..."),
            convert("..OO."),
            convert("....O"),
            convert("..OO."),
            convert("OO..."),
            convert("....."),
            convert("....."),
        ]),
        '/' => Some([
            convert("....."),
            convert("...O."),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert(".O..."),
            convert(".O..."),
            convert("....."),
        ]),
        '\\' => Some([
            convert("....."),
            convert(".O..."),
            convert(".O..."),
            convert("..O.."),
            convert("..O.."),
            convert("..O.."),
            convert("...O."),
            convert("...O."),
            convert("....."),
        ]),
        '?' => Some([
            convert("....."),
            convert(".OOO."),
            convert("O...O"),
            convert("...O."),
            convert("..O.."),
            convert("..O.."),
            convert("....."),
            convert("..O.."),
            convert("....."),
        ]),
        ',' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OO.."),
            convert("...O."),
            convert("..O.."),
            convert("....."),
        ]),
        '.' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert(".OO.."),
            convert(".OO.."),
            convert("....."),
            convert("....."),
        ]),
        '_' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("OOOOO"),
            convert("....."),
        ]),
        ' ' => Some([
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
            convert("....."),
        ]),
        _ => None,
    }
}

pub fn scale_glyph(ch: char, scale: usize, alpha: u8) -> Vec<u8> {
    let scale = scale.max(1);
    let sw = CHAR_W * scale;
    let sh = CHAR_H * scale;

    let Some(base) = get_glyph(ch) else {
        return vec![0; sw * sh * 4];
    };

    let mut buf = vec![0u8; sw * sh * PIXEL_BIT];

    for (y, bpix) in base.iter().enumerate().take(CHAR_H) {
        for x in 0..CHAR_W {
            if (bpix >> (CHAR_W - 1 - x)) & 1 == 1 {
                for dy in 0..scale {
                    for dx in 0..scale {
                        let i = ((x * scale + dx) + (y * scale + dy) * sw) * PIXEL_BIT;
                        buf[i..i + 4].copy_from_slice(&[150, 220, 255, alpha]);
                    }
                }
            }
        }
    }

    buf
}

pub fn roll_one(list: &str) -> char {
    let list = list.replace(|c| get_glyph(c).is_none(), "");

    list.chars()
        .nth(rand::random_range(0..list.len()))
        .unwrap_or('_')
}

pub fn rolln(list: &str, target: char, max_roll: usize) -> Vec<char> {
    let mut res = vec![];

    for i in 1..=max_roll {
        if i == max_roll {
            res.push(target);

            break;
        }

        let rolled = roll_one(list);

        res.push(rolled);

        if rolled == target {
            break;
        }
    }

    res
}
